services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lareserva
      SPRING_DATASOURCE_USERNAME: lareserva
      SPRING_DATASOURCE_PASSWORD: 1VvvT0Ub9efOd2Ml99SmDPihIT1dn6OB
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lareserva
      POSTGRES_PASSWORD: 1VvvT0Ub9efOd2Ml99SmDPihIT1dn6OB
      POSTGRES_DB: lareserva
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lareserva" ]
      interval: 5s
      retries: 5
      timeout: 3s